### ISSUE TITLE
`pip check` fails with pip==24.2: upf-to-json is not supported on this platform

### ISSUE THREAD

**Issue by danielhollas** [conda-forge/upf_to_json-feedstock#4]
### Issue

Running a `pip check` in a fresh conda environment with latest pip==24.2 reports a problem that's likely caused by invalid wheel metadata. More info and discussion can be found on this issue:
https://github.com/pypa/pip/issues/11054

To reproduce
```
$ conda create -n test pip=22.4 upf-to-json
$ conda activate test
$ pip check
upf-to-json 0.9.2 is not supported on this platform
```

Note that `pip check` does not fail if the `upf-to-json` package is installed with pip from PYPI.

**Comment by danielhollas** [comment]
Looks like just rebuilding the package solves this issue. I've opened #5 and added `pip check` to tests.

**Comment by simonpintarelli** [comment]
Thank you @danielhollas for the help.

**Comment by danielhollas** [comment]
It looks like the problem is an incorrect Python version tag is specified in the `*.dist-info/WHEEL` file. Here's the  content of the file in the current build.

```
Wheel-Version: 1.0
Generator: bdist_wheel (0.33.6)
Root-Is-Purelib: true
Tag: cp27-none-any
```

`cp27` means that the package is restricted to CPython 2.7. Instead, to support both Python 2 to and Python 3, the platform tag should be `py2.py3` per specification here: https://packaging.python.org/en/latest/specifications/platform-compatibility-tags/#python-tag
